# Задача 1
## Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
## Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
## Полученные значения должны быть равны.
## Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
## а затем с использованием функций из библиотек numpy и pandas.


In [1]:
import numpy as np
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [8]:
M_zp = zp.mean()
M_zp

101.4

In [9]:
M_ks = ks.mean()
M_ks

709.9

In [13]:
total = zp*ks
total


array([ 14035,  25830, 166060, 183800,  18360,  51730,  35262, 135300,
        89520,  91520])

In [14]:
M_total = total.mean()
M_total

81141.7

In [15]:
cov = M_total - M_ks * M_zp
cov

9157.839999999997

In [12]:
np.cov(zp, ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [17]:
np.cov(zp, ks, ddof = 0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Смещенная ковариация, расчитанная функцией, равна рассчитанной нами по формуле.

In [19]:
s1 = np.std(zp, ddof = 0)
s1

59.115480206118605

In [20]:
s2 = np.std(ks, ddof = 0)
s2

174.55340157098058

In [21]:
r = cov/(s1*s2)
r

0.8874900920739158

In [22]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Коэффициенты корреляции расчитанные по формуле и через функцию библиотеки numpy совпадают.

# Задача 2

## Измерены значения IQ выборки студентов,
## обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
## Известно, что в генеральной совокупности IQ распределен нормально.
## Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [27]:
X = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
M = X.mean()
M

118.1

In [30]:
D1 = np.var(X, ddof=1)
D1

111.21111111111111

In [29]:
len(X)

10

Поскольку неизвестно среднее квадратичное генеральной совокупности, то используем критерий Стьюдента: распределение Стьюдента зависит от степеней свободы (n - 1). α/2 = 0.025

По таблице берем параметры 0.975 для p и 9 степеней свободы. Получаем t=2.262

In [31]:
t = 2.262
M - t*np.sqrt(D1/10)

110.55660776308164

In [32]:
M + t*np.sqrt(D1/10)

125.64339223691834

In [33]:
Ответ: (110.56, 125.64)

# Задача 3

## Известно, что рост футболистов в сборной распределен нормально
## с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
## среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
## ожидания с надежностью 0.95.

Поскольку известна дисперсия генеральной совокупности, то используем формулу с z критерием.

In [34]:
S = np.sqrt(25)
S

5.0

z = 1.96(для alpha = 5%)

In [35]:
m = 174.2
n = 27
m - 1.96*(S/np.sqrt(n))

172.31398912064722

In [36]:
m + 1.96*(S/np.sqrt(n))

176.08601087935276

Ответ: (172.31, 176.09)